server:
    port: 9010

extender:
    sdk:
        location: /usr/local/extender/sdk
        cache-clear-on-exit: false
    cache:
        enabled: false
    remote-builder:
        enabled: false
    cocoapods:
        enabled: true
        home-dir-prefix: /usr/local/extender/.cocoapods
        repo-update-cron: "0 0 * * * *" # update spec repo every 1 h
        cache-dir-rotate-cron: "0 10 2 * * *" # once per day
        old-cache-clean-cron: "0 10 6 * * *" # once per day after directory rotation
