extender:
    instance-type: FRONTEND_ONLY
    remote-builder:
        enabled: true
        platforms:
            android-ndk25:
                url: http://android-ndk25:9000
                instanceId: android-ndk25
                alwaysOn: true
            emsdk-3165:
                url: http://emsdk-3165:9000
                instanceId: emsdk-3165
            emsdk-406:
                url: http://emsdk-406:9000
                instanceId: emsdk-406
            linux-latest:
                url: http://linux:9000
                instanceId: linux
            linux-arm64-latest:
                url: http://linux-arm64:9000
                instanceId: linux-arm64
            nssdk-1832:
                url: http://nssdk-1832:9000
                instanceId: nssdk-1832
            ps4-12500:
                url: http://ps4-12500:9000
                instanceId: ps4-12500
            ps5-12000:
                url: http://ps5-12000:9000
                instanceId: ps5-12000
            winsdk-2022:
                url: http://winsdk-2022:9000
                instanceId: winsdk-2022
            xbox-251001:
                url: http://xbox-251001:9000
                instanceId: xbox-251001

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
